spring:
  application:
    name: notification-service
  cloud:
    stream:
      bindings:
        stockVerificationEmail-in-0:
          destination: stockVerificationEmail-topic
        productsRequestEmail-in-0:
          destination: productsRequestEmail-topic
        productsRequestDecisionEmail-in-0:
          destination: productsRequestDecisionEmail-topic
    function:
      definition: stockVerificationEmail;productsRequestEmail;productsRequestDecisionEmail
      kafka:
        binder:
          brokers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: imabionoor@gmail.com
    password: dfkd cljn idcp vudl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 0
